services:
  db:
    image: postgres:18.0
    container_name: "relational_db"
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 60s
    secrets:
      - db_password_secret
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_secret
      POSTGRES_DB: markivio
    volumes:
      - db_data_volume:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: db_management
    ports:
      - 8082:8080

  db-updater:
    build:
      context: ./backend/api/
      dockerfile: Dockerfile.DbUpdater
    container_name: "updater"
    env_file: ./backend/api/dev.env
    depends_on:
      db:
        condition: service_healthy

  graphql_api:
    build:
      context: ./backend/api/
      dockerfile: Dockerfile.Api
      args:
        COMPIL_MODE: Debug
    ports:
      - 8080:8080
    env_file: ./backend/api/dev.env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      db-updater:
        condition: service_completed_successfully
    develop:
      watch:
        - action: rebuild
          path: ./backend/api
          ignore: 
            - ./backend/api/**/bin
            - ./backend/api/**/obj

  frontend:
    build:
      context: ./frontend/markivio-frontend
      dockerfile: Dockerfile.dev
    container_name: webapp-frontend
    ports:
      - 5173:5173
    depends_on:
      - graphql_api
    develop:
      watch:
        - action: rebuild
          path: ./frontend/markivio-frontend/package.json
        - action: sync
          path: ./frontend/markivio-frontend
          target: /app
          ignore:
            - ./frontend/markivio-frontend/node_modules



secrets:
  db_password_secret:
    file: ./psql-secret.txt

volumes:
  db_data_volume:
